name: Test action

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev

jobs:
  bundle_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build bundle
        uses: ./.github/actions/bundle
        with:
          path: test/manifest.yml
          channel: dev
